name: policy test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-iam-policies:
    name: Validate IAM Policies
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Devolv
        run: pip install devolv

      - name: Run Devolv on policy folder
        run: devolv validate sample_policies
    continue-on-error: true